{% set name = "sqlalchemy-bigquery" %}
{% set version = "1.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy-bigquery-{{ version }}.tar.gz
  sha256: 2ad1210b80e937da4eb56422ab83dddb8ec172f3311c81fd0a3b4fd1e482477f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6,<3.11
    - pip
  run:
    - python >=3.6,<3.11
    - future
    - google-api-core >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - google-auth >=1.25.0,<3.0.0dev
    - google-cloud-bigquery >=2.25.2,<3.0.0dev
    - sqlalchemy >=1.2.0,<=1.4.27

test:
  imports:
    - sqlalchemy_bigquery
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-bigquery-sqlalchemy
  summary: SQLAlchemy dialect for BigQuery
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
